// Default Bip001 → Mixamo bone name mapping.
// Keys:   Bip001 bone names (FBXLoader sanitises spaces→underscores).
// Values: Mixamo bone names (FBXLoader strips the colon from "mixamorig:Hips").
//
// This record is the single source of truth — it lives here so the store,
// the retargeter, and the BoneMapEditor all share the same default.

export const DEFAULT_BONE_MAP: Record<string, string> = {
  Bip001_Pelvis:     "mixamorigHips",
  Bip001_Spine:      "mixamorigSpine",
  Bip001_Neck:       "mixamorigNeck",
  Bip001_Head:       "mixamorigHead",
  Bip001_L_Clavicle: "mixamorigLeftShoulder",
  Bip001_L_UpperArm: "mixamorigLeftArm",
  Bip001_L_Forearm:  "mixamorigLeftForeArm",
  Bip001_L_Hand:     "mixamorigLeftHand",
  Bip001_R_Clavicle: "mixamorigRightShoulder",
  Bip001_R_UpperArm: "mixamorigRightArm",
  Bip001_R_Forearm:  "mixamorigRightForeArm",
  Bip001_R_Hand:     "mixamorigRightHand",
  Bip001_L_Thigh:    "mixamorigLeftUpLeg",
  Bip001_L_Calf:     "mixamorigLeftLeg",
  Bip001_L_Foot:     "mixamorigLeftFoot",
  Bip001_L_Toe0:     "mixamorigLeftToeBase",
  Bip001_R_Thigh:    "mixamorigRightUpLeg",
  Bip001_R_Calf:     "mixamorigRightLeg",
  Bip001_R_Foot:     "mixamorigRightFoot",
  Bip001_R_Toe0:     "mixamorigRightToeBase",
};

// Canonical display order for the BoneMapEditor (anatomical, head-to-toe).
export const BIP001_ORDERED = [
  "Bip001_Pelvis",
  "Bip001_Spine",
  "Bip001_Neck",
  "Bip001_Head",
  "Bip001_L_Clavicle",
  "Bip001_L_UpperArm",
  "Bip001_L_Forearm",
  "Bip001_L_Hand",
  "Bip001_R_Clavicle",
  "Bip001_R_UpperArm",
  "Bip001_R_Forearm",
  "Bip001_R_Hand",
  "Bip001_L_Thigh",
  "Bip001_L_Calf",
  "Bip001_L_Foot",
  "Bip001_L_Toe0",
  "Bip001_R_Thigh",
  "Bip001_R_Calf",
  "Bip001_R_Foot",
  "Bip001_R_Toe0",
] as const;

// All standard Mixamo bones we ever deal with (no finger/toe-end clutter).
export const MIXAMO_ORDERED = [
  "mixamorigHips",
  "mixamorigSpine",
  "mixamorigSpine1",
  "mixamorigSpine2",
  "mixamorigNeck",
  "mixamorigHead",
  "mixamorigLeftShoulder",
  "mixamorigLeftArm",
  "mixamorigLeftForeArm",
  "mixamorigLeftHand",
  "mixamorigRightShoulder",
  "mixamorigRightArm",
  "mixamorigRightForeArm",
  "mixamorigRightHand",
  "mixamorigLeftUpLeg",
  "mixamorigLeftLeg",
  "mixamorigLeftFoot",
  "mixamorigLeftToeBase",
  "mixamorigRightUpLeg",
  "mixamorigRightLeg",
  "mixamorigRightFoot",
  "mixamorigRightToeBase",
] as const;

export const BIP001_LABELS: Record<string, string> = {
  Bip001_Pelvis:     "Pelvis",
  Bip001_Spine:      "Spine",
  Bip001_Neck:       "Neck",
  Bip001_Head:       "Head",
  Bip001_L_Clavicle: "L Clav",
  Bip001_L_UpperArm: "L UpArm",
  Bip001_L_Forearm:  "L Forearm",
  Bip001_L_Hand:     "L Hand",
  Bip001_R_Clavicle: "R Clav",
  Bip001_R_UpperArm: "R UpArm",
  Bip001_R_Forearm:  "R Forearm",
  Bip001_R_Hand:     "R Hand",
  Bip001_L_Thigh:    "L Thigh",
  Bip001_L_Calf:     "L Calf",
  Bip001_L_Foot:     "L Foot",
  Bip001_L_Toe0:     "L Toe",
  Bip001_R_Thigh:    "R Thigh",
  Bip001_R_Calf:     "R Calf",
  Bip001_R_Foot:     "R Foot",
  Bip001_R_Toe0:     "R Toe",
};

export const MIXAMO_LABELS: Record<string, string> = {
  mixamorigHips:          "Hips",
  mixamorigSpine:         "Spine",
  mixamorigSpine1:        "Spine1",
  mixamorigSpine2:        "Spine2",
  mixamorigNeck:          "Neck",
  mixamorigHead:          "Head",
  mixamorigLeftShoulder:  "L Shoulder",
  mixamorigLeftArm:       "L Arm",
  mixamorigLeftForeArm:   "L ForeArm",
  mixamorigLeftHand:      "L Hand",
  mixamorigRightShoulder: "R Shoulder",
  mixamorigRightArm:      "R Arm",
  mixamorigRightForeArm:  "R ForeArm",
  mixamorigRightHand:     "R Hand",
  mixamorigLeftUpLeg:     "L UpLeg",
  mixamorigLeftLeg:       "L Leg",
  mixamorigLeftFoot:      "L Foot",
  mixamorigLeftToeBase:   "L ToeBase",
  mixamorigRightUpLeg:    "R UpLeg",
  mixamorigRightLeg:      "R Leg",
  mixamorigRightFoot:     "R Foot",
  mixamorigRightToeBase:  "R ToeBase",
};

// Color per Bip001 bone (anatomical grouping).
export const BIP001_COLORS: Record<string, string> = {
  Bip001_Pelvis:     "#f59e0b",
  Bip001_Spine:      "#f59e0b",
  Bip001_Neck:       "#a78bfa",
  Bip001_Head:       "#a78bfa",
  Bip001_L_Clavicle: "#fb923c",
  Bip001_L_UpperArm: "#fb923c",
  Bip001_L_Forearm:  "#fb923c",
  Bip001_L_Hand:     "#fb923c",
  Bip001_R_Clavicle: "#34d399",
  Bip001_R_UpperArm: "#34d399",
  Bip001_R_Forearm:  "#34d399",
  Bip001_R_Hand:     "#34d399",
  Bip001_L_Thigh:    "#38bdf8",
  Bip001_L_Calf:     "#38bdf8",
  Bip001_L_Foot:     "#38bdf8",
  Bip001_L_Toe0:     "#38bdf8",
  Bip001_R_Thigh:    "#f472b6",
  Bip001_R_Calf:     "#f472b6",
  Bip001_R_Foot:     "#f472b6",
  Bip001_R_Toe0:     "#f472b6",
};
